CREATE DATABASE test;

USE test;

CREATE TABLE t_user(
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL ,
  password VARCHAR(255) NOT NULL ,
  phone VARCHAR(255) NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


INSERT INTO `test`.`t_user`(`id`, `name`, `password`, `phone`) VALUES (1001, '张三', '123', '18826071570');
